# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-30 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Name of Sponsor'),
        ),
    ]
