# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-05 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_auto_20170901_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='losses',
            field=models.PositiveIntegerField(default=0, verbose_name='Total loss'),
        ),
        migrations.AddField(
            model_name='team',
            name='wins',
            field=models.PositiveIntegerField(default=0, verbose_name='Total wins'),
        ),
    ]
