# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-05 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_auto_20170905_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='knockout',
            field=models.BooleanField(default=False, verbose_name='is a Knockout'),
        ),
    ]
