# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-05 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0008_team_knockout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team_a_score',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_b_score',
            field=models.SmallIntegerField(default=0),
        ),
    ]
