# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-09 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0009_auto_20170905_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
