# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-09 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0010_player_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField(verbose_name='rule')),
            ],
        ),
        migrations.CreateModel(
            name='Standings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveIntegerField()),
                ('wins', models.PositiveIntegerField(default=0, verbose_name='Total wins')),
                ('draws', models.PositiveIntegerField(default=0, verbose_name='Total draws')),
                ('losses', models.PositiveIntegerField(default=0, verbose_name='Total loss')),
                ('goals_f', models.PositiveIntegerField(default=0, verbose_name='Goals F')),
                ('goals_a', models.PositiveIntegerField(default=0, verbose_name='Goals A')),
                ('goals_d', models.PositiveIntegerField(default=0, verbose_name='Goals D')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Points')),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='knockout',
        ),
        migrations.RemoveField(
            model_name='team',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='team',
            name='wins',
        ),
        migrations.AddField(
            model_name='standings',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Team'),
        ),
    ]
