# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-09 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0011_auto_20170909_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standings',
            options={'ordering': ['place']},
        ),
        migrations.AddField(
            model_name='standings',
            name='gp',
            field=models.PositiveIntegerField(default=0, verbose_name='Games Played'),
        ),
        migrations.AlterField(
            model_name='standings',
            name='place',
            field=models.PositiveIntegerField(verbose_name='Team ranking'),
        ),
    ]
