# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-16 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0013_auto_20170909_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team_a_score',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_b_score',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
