# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-16 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0014_auto_20170916_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='message_a',
            field=models.TextField(blank=True, null=True, verbose_name='Message A'),
        ),
        migrations.AddField(
            model_name='match',
            name='message_b',
            field=models.TextField(blank=True, null=True, verbose_name='Message B'),
        ),
        migrations.AddField(
            model_name='match',
            name='penalty_a_score',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='penalty_b_score',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
