# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-16 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0015_auto_20170916_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='message_a',
            field=models.TextField(blank=True, null=True, verbose_name='Team A score timings'),
        ),
        migrations.AlterField(
            model_name='match',
            name='message_b',
            field=models.TextField(blank=True, null=True, verbose_name='Team B score timings'),
        ),
    ]
